### ISSUE TITLE
Hide Pixxio Button in Contentblocks where maxitems is reached

### ISSUE THREAD

**Issue by EricVonBrumby** [pixx-io/typo3#44]
## Environment

    TYPO3 Version: 12.4.28

    PHP Version: 8.3

    Pixxio Extension: 2.1.1

## Issue Description

We are using Content Blocks in combination with the Pixxio Extension.

Generally, everything works as expected. However, we encountered a UX issue:

When the maxitems limit is reached (e.g., 1 image), the Pixxio button remains visible. This suggests that users can still add more images, even though the limit has been reached. This behavior is confusing and misleading.

## Configuration Example
```yaml
[...]
fields:
  - identifier: image
    type: File
    allowed: common-image-types
    maxitems: 1
    useExistingField: true
```

## Screenshot

![Image](https://github.com/user-attachments/assets/c1941f27-36a9-412e-b248-a5af93c08931)

## Expected Behavior

We would expect the Pixxio button to be automatically hidden when the configured maxitems limit is reached.

## Question

Is there a supported way (or workaround) to hide the Pixxio button dynamically when the item limit is reached?
Many thanks in advance!
